name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  use-commit-message:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CD repository
        uses: actions/checkout@v4
        with:
          repository: ekchoi391204/k8s-helm2
          ref: main
          token: ${{ secrets.TOKEN }}  # Personal Access Token 사용

      - name: Update app.tag in values.yaml using commit message
        run: |
          SAFE_TAG=$(echo "${{ github.event.workflow_run.head_commit.message }}" | tr -s ' ' '-' | tr -dc '[:alnum:]-')
          echo "Using tag: $SAFE_TAG"

          awk -v tag="$SAFE_TAG" '
          /^app:/ { in_app=1; print; next }
          in_app && /^\s*tag:/ {
            print "  tag: " tag
            in_app=0
            next
          }
          { print }
          ' values.yaml > tmp.yaml && mv tmp.yaml values.yaml

      - name: Set up Git user
        run: |
          git config --global user.name "ekchoi3912"
          git config --global user.email "ekchoi391204@gmail.com"

      - name: Commit and push changes
        run: |
          git add values.yaml
          git commit -m "Update app tag from commit message" || echo "No changes to commit"
          git push origin main
