name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  use-commit-message:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CD repository
        uses: actions/checkout@v4
        with:
          repository: ekchoi391204/k8s-helm2
          ref: main
          token: ${{ secrets.TOKEN }}  # Personal Access Token 사용

      - name: Get commit message from CI workflow
        id: get_message
        run: |
          COMMIT_MESSAGE=$(gh api repos/${{ github.repository }}/commits/${{ github.event.workflow_run.head_sha }} --jq .commit.message)
          echo "message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}

      - name: Update tag in values.yaml
        run: |
          cd charts/myapp
          sed -i "s/^\(\s*tag:\s*\).*/\1${{ steps.get_message.outputs.message }}/" values.yaml

      - name: Set up Git user
        run: |
          git config --global user.name "ekchoi3912"
          git config --global user.email "ekchoi391204@gmail.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "${{ steps.get_message.outputs.message }}" || echo "No changes to commit"
          git push origin main
